development:
  adapter: postgresql
  encoding: unicode
  database: tv_app_development
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 092788
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: tv_app_test
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 092788
  port: 5432